"use client";

import { useEffect, useMemo, useState } from "react";
import { productCatalog } from "../catalog";
import { LeadForm } from "../components/lead-form";
import { SalesShell } from "../components/sales-shell";

export default function QuotePage(){ const [space,setSpace]=useState("restaurant"); const [area,setArea]=useState(80); const [problem,setProblem]=useState("flies"); const [preset,setPreset]=useState(""); const [extra,setExtra]=useState(""); useEffect(()=>{const q=new URLSearchParams(location.search);
  // Planner handoff values are only available after hydration.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setPreset(q.get("product")||"");setArea(Number(q.get("area"))||80);setExtra(q.get("details")||"")},[]); const product=useMemo(()=>productCatalog.find(p=>p.slug===preset)||productCatalog.find(p=>space==="production"?p.slug==="prolit":space==="warehouse"?p.slug==="pro202":space==="hotel"?p.slug==="mood":p.slug==="magnet")!,[space,preset]); const count=Math.max(1,Math.ceil(area/product.planningCoverage*(space==="production"?1.3:1))); return <SalesShell>{language=>{const c={tr:{k:"Hızlı teklif",title:"Üç seçimde doğru başlangıç.",desc:"Mekânı ve sorunu anlatın; sistem uygun Dudexa çözümünü teklif talebinize eklesin.",space:"Mekân türü",area:"Alan (m²)",problem:"Sorun",result:"Önerilen başlangıç",unit:"cihaz",note:"Saha koşullarına göre Dudexa ekibi nihai seçimi teyit eder."},en:{k:"Quick quote",title:"The right start in three choices.",desc:"Describe the space and pressure; the system adds a suitable Dudexa solution to your request.",space:"Space type",area:"Area (m²)",problem:"Problem",result:"Recommended start",unit:"units",note:"The Dudexa team confirms the final selection for site conditions."},zh:{k:"快速报价",title:"三步获得合适起点。",desc:"选择空间和虫害情况，系统会将合适的 Dudexa 方案加入询价。",space:"空间类型",area:"面积（m²）",problem:"虫害情况",result:"建议起点",unit:"台",note:"Dudexa 团队将根据现场条件确认最终方案。"}}[language]; const details=`${extra}\nWizard: ${space}, ${area}m², ${problem}. Recommendation: ${count} × ${product.name}.`; return <><section className="feature-hero"><span className="sales-kicker">{c.k}</span><h1>{c.title}</h1><p>{c.desc}</p></section><section className="wizard"><div className="wizard-controls"><label className="sales-field">{c.space}<select value={space} onChange={e=>{setSpace(e.target.value);setPreset("")}}><option value="restaurant">Restaurant / Café</option><option value="hotel">Hotel</option><option value="retail">Retail</option><option value="production">Food production</option><option value="warehouse">Warehouse</option></select></label><label className="sales-field">{c.area}<input type="number" min="10" max="5000" value={area} onChange={e=>setArea(Number(e.target.value)||10)}/></label><label className="sales-field">{c.problem}<select value={problem} onChange={e=>setProblem(e.target.value)}><option value="flies">House flies</option><option value="small-flies">Small flies</option><option value="night-insects">Night flying insects</option><option value="mixed">Mixed pressure</option></select></label><LeadForm language={language} source="quick-quote" product={product.name} details={details}/></div><div className="wizard-result"><span>{c.result}</span><h2>{count} ×<br/>{product.name}</h2><p>{product.use[language]}<br/>{c.note}</p></div></section></>;}}</SalesShell> }
