import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { productCatalog } from "../../catalog";

const solutions={"industrial-insect-light-trap":{title:"Industrial insect light traps for demanding facilities",description:"Plan UV-A glue-board insect light traps for food production, warehouses and commercial hygiene programs.",products:["prolit","pro202"],keywords:["industrial insect light trap","food production fly control","warehouse insect light trap"]},"uv-insect-trap":{title:"Professional UV insect traps with discreet glue-board capture",description:"Compare wall-mounted and suspended Dudexa UV-A insect traps for hospitality, retail and commercial environments.",products:["mood","magnet","fli-x"],keywords:["UV insect trap","commercial fly light","glue board insect trap"]}} as const;
export function generateStaticParams(){return Object.keys(solutions).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const item=solutions[(await params).slug as keyof typeof solutions];if(!item)return{};return{title:`${item.title} — Dudexa`,description:item.description,keywords:[...item.keywords],alternates:{canonical:`/solutions/${(await params).slug}`}}}
export default async function SolutionPage({params}:{params:Promise<{slug:string}>}){const slug=(await params).slug;const item=solutions[slug as keyof typeof solutions];if(!item)notFound();const products=productCatalog.filter(p=>(item.products as readonly string[]).includes(p.slug));return <main className="sales-page"><header className="sales-nav"><Link className="brand" href="/">DDX<span>•</span></Link><nav><Link href="/#products">Products</Link><Link href="/planner">Coverage planner</Link><Link href="/documents">Documents</Link></nav><Link className="sales-contact" href="/quote">Request quote ↗</Link></header><section className="feature-hero"><span className="sales-kicker">Dudexa / Solution guide</span><h1>{item.title}</h1><p>{item.description}</p></section><section className="sales-section"><div className="card-grid">{products.map(product=><article className="seo-card" key={product.slug}><img src={product.image} alt={`Dudexa ${product.name}`} style={{width:"100%",height:"220px",objectFit:"contain"}}/><h2>{product.name}</h2><p>{product.summary.en}</p><Link className="sales-button" href={`/products/${product.slug}`}>View product ↗</Link></article>)}</div></section><section className="seo-cta"><h2>Plan the right number of units for your space.</h2><Link className="sales-button" href="/planner">Open planner ↗</Link></section></main>}
